'*.{ts,tsx,js}':
  - 'eslint --cache --cache-location ./node_modules/.cache/.eslintcache --fix'
  - 'prettier --log-level warn --cache --write'
'*.{json,yml,scss,css}': 'prettier --log-level warn --cache --write'
